AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  InlineLamda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.handler
      Runtime: python3.12
      PackageType: Zip
      CodeUri: "./function/"